
DATABASE_ENGINE='mysql'
DATABASE_HOST = 'localhost'
DATABASE_NAME='learning-db'
DATABASE_USERNAME ='root'
DATABASE_USER_PASSWORD = ''
DATABASE_PORT = '3306'
SQLITE_URI = f'sqlite:////tmp/{DATABASE_NAME}.db'

SQLALCHEMY_DATABASE_URI=f'{DATABASE_ENGINE}+pymysql://{DATABASE_USERNAME}:{DATABASE_USER_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'

print("SQLALCHEMY_DATABASE_URI ==>",SQLALCHEMY_DATABASE_URI)