
DATABASE_ENGINE='mysql'
DATABASE_HOST = 'localhost'
DEV_DATABASE_NAME='librarie-db-dev'
PROD_DATABASE_NAME='librarie-db-prod'
TEST_DATABASE_NAME='librarie-db-test'
SQLITE_DATABASE = 'local-db'
DATABASE_USERNAME ='root'
DATABASE_USER_PASSWORD = ''
DATABASE_PORT = '3306'
SQLITE_URI = f'sqlite:////tmp/{SQLITE_DATABASE}.db'

import secrets
JWT_SECRET_KEY = secrets.token_hex(16)
print('KEY ==>', JWT_SECRET_KEY)


class Config(object):
    DEBUG = False
    TESTING = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False

class ProductionConfig(Config):
    SQLALCHEMY_DATABASE_URI=f'{DATABASE_ENGINE}+pymysql://{DATABASE_USERNAME}:{DATABASE_USER_PASSWORD}@{PROD_DATABASE_NAME}:{DATABASE_PORT}/{DEV_DATABASE_NAME}'

class DevelopmentConfig(Config):
    SQLALCHEMY_DATABASE_URI = f'{DATABASE_ENGINE}+pymysql://{DATABASE_USERNAME}:{DATABASE_USER_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DEV_DATABASE_NAME}'
    DEBUG = True
    SQLALCHEMY_ECHO = False

class TestingConfig(Config):
    SQLALCHEMY_DATABASE_URI = f'{DATABASE_ENGINE}+pymysql://{DATABASE_USERNAME}:{DATABASE_USER_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{TEST_DATABASE_NAME}'
    DEBUG = True
    SQLALCHEMY_ECHO = False